const inputFile = (name, flag, options = {}) => ({ name, flag, type: 'path', pathKind: 'input-file', ...options })
const inputDir = (name, flag, options = {}) => ({ name, flag, type: 'path', pathKind: 'input-dir', ...options })
const inputPath = (name, flag, options = {}) => ({ name, flag, type: 'path', pathKind: 'input-path', ...options })
const outputFile = (name, flag, options = {}) => ({ name, flag, type: 'path', pathKind: 'output-file', ...options })
const outputDir = (name, flag, options = {}) => ({ name, flag, type: 'path', pathKind: 'output-dir', ...options })
const value = (name, flag, type = 'string', options = {}) => ({ name, flag, type, ...options })

export const HELPER_CATALOG = [
  {
    name: 'animation-contact-sheet',
    module: 'animation-quality-gate',
    description: 'Combine rendered animation frames into a labeled contact sheet and flag large frame-to-frame visual jumps.',
    runtime: 'python',
    dependencies: ['Pillow'],
    script: 'references/modules/animation-quality-gate/scripts/animation_contact_sheet.py',
    arguments: [
      { name: 'frames', flag: '--frames', type: 'path-array', pathKind: 'input-file', required: true },
      outputFile('out_image', '--out-image', { required: true }),
      outputFile('out_report', '--out-report', { required: true }),
      value('cols', '--cols', 'integer'),
    ],
  },
  {
    name: 'atlas-region-detector',
    module: 'atlas-uv-fitting',
    description: 'Detect occupied regions in a texture atlas and write measurable UV-region candidates.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/atlas-uv-fitting/scripts/atlas_region_detector.py',
    arguments: [
      inputFile('image', '--image', { required: true }),
      outputFile('out', '--out', { required: true }),
      value('mode', '--mode', 'string', { choices: ['auto', 'alpha', 'bright_on_dark', 'dark_on_bright'] }),
      value('min_area', '--min-area', 'integer'),
      value('pad', '--pad', 'integer'),
    ],
  },
  {
    name: 'atlas-region-mapper',
    module: 'atlas-uv-fitting',
    description: 'Match segmented source parts to detected atlas regions and emit ranked mapping candidates.',
    runtime: 'python',
    dependencies: [],
    script: 'references/modules/atlas-uv-fitting/scripts/atlas_region_mapper.py',
    arguments: [
      inputFile('parts', '--parts', { required: true }),
      inputFile('regions', '--regions', { required: true }),
      outputFile('out', '--out', { required: true }),
      value('max_candidates', '--max-candidates', 'integer'),
    ],
  },
  {
    name: 'skill-graph-audit',
    module: 'blender-skill-harmonizer',
    description: 'Audit a Blender skill graph and report unresolved references or missing harmonization.',
    runtime: 'python',
    dependencies: [],
    maintenance: true,
    script: 'references/modules/blender-skill-harmonizer/scripts/skill_graph_audit.py',
    arguments: [
      inputDir('plugin_root', '--plugin-root'),
      outputFile('out', '--out', { required: true }),
    ],
  },
  {
    name: 'surface-texture-coverage-audit',
    module: 'closed-surface-uv-coverage',
    description: 'Audit mesh UV layers, material slots, and image-texture coverage inside a Blender scene.',
    runtime: 'blender',
    dependencies: [],
    requiresBlend: true,
    script: 'references/modules/closed-surface-uv-coverage/scripts/surface_texture_coverage_audit.py',
    arguments: [
      value('objects', '--objects', 'string-array'),
      outputFile('out', '--out'),
    ],
  },
  {
    name: 'mask-to-mesh-recipe',
    module: 'contour-to-mesh',
    description: 'Extract a source contour and emit a deterministic mesh recipe plus optional Blender Python.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy', 'scipy'],
    script: 'references/modules/contour-to-mesh/scripts/mask_to_mesh_recipe.py',
    arguments: [
      inputFile('image', '--image', { required: true }),
      value('name', '--name', 'string', { required: true }),
      outputFile('out', '--out', { required: true }),
      outputFile('blender_script', '--blender-script'),
      value('world_width', '--world-width', 'number'),
      value('samples', '--samples', 'integer'),
      value('mode', '--mode', 'string', { choices: ['auto', 'alpha', 'edges', 'bright_on_dark', 'dark_on_bright'] }),
    ],
  },
  {
    name: 'source-locked-skin-recipe',
    module: 'contour-to-mesh',
    description: 'Build a dense source-locked front-surface recipe and its selected binary mask.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy', 'scipy'],
    script: 'references/modules/contour-to-mesh/scripts/source_locked_skin_recipe.py',
    arguments: [
      inputFile('image', '--image', { required: true }),
      outputFile('out', '--out', { required: true }),
      outputFile('mask_out', '--mask-out', { required: true }),
      value('name', '--name'),
      value('world_width', '--world-width', 'number'),
      value('samples', '--samples', 'integer'),
      value('mode', '--mode', 'string', { choices: ['green_yellow', 'bright', 'non_dark', 'otsu', 'alpha'] }),
      value('hue_min', '--hue-min', 'integer'),
      value('hue_max', '--hue-max', 'integer'),
      value('sat_min', '--sat-min', 'integer'),
      value('value_min', '--value-min', 'integer'),
      value('close_iters', '--close-iters', 'integer'),
      value('open_ksize', '--open-ksize', 'integer'),
      value('dilate_iters', '--dilate-iters', 'integer'),
      value('epsilon_frac', '--epsilon-frac', 'number'),
    ],
  },
  {
    name: 'fit-repair-queue',
    module: 'fit-repair-optimizer',
    description: 'Convert fit and look reports into a dependency-aware geometry, UV, look, and export repair queue.',
    runtime: 'python',
    dependencies: [],
    script: 'references/modules/fit-repair-optimizer/scripts/fit_repair_queue.py',
    arguments: [
      inputFile('fit_report', '--fit-report', { required: true }),
      inputFile('texture_lighting_report', '--texture-lighting-report'),
      outputFile('out', '--out', { required: true }),
      outputFile('method_md', '--method-md'),
    ],
  },
  {
    name: 'landmark-fit-report',
    module: 'landmark-fit-repair',
    description: 'Compare named source and product landmarks and report pixel deltas against a tolerance.',
    runtime: 'python',
    dependencies: [],
    script: 'references/modules/landmark-fit-repair/scripts/landmark_fit_report.py',
    arguments: [
      inputFile('source', '--source', { required: true }),
      inputFile('product', '--product', { required: true }),
      outputFile('out', '--out', { required: true }),
      value('tolerance_px', '--tolerance-px', 'number'),
    ],
  },
  {
    name: 'view-constraint-report',
    module: 'multiview-constraint-solver',
    description: 'Detect contradictory shared-axis dimensions across front, side, back, and top view bboxes.',
    runtime: 'python',
    dependencies: [],
    script: 'references/modules/multiview-constraint-solver/scripts/view_constraint_report.py',
    arguments: [
      inputFile('input', '--input', { required: true }),
      outputFile('out', '--out', { required: true }),
      value('tolerance', '--tolerance', 'number'),
    ],
  },
  {
    name: 'multiview-fit-report',
    module: 'multiview-fit-loop',
    description: 'Compare registered front, side, back, and top template/render pairs and save overlays plus fit metrics.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/multiview-fit-loop/scripts/multiview_fit_report.py',
    arguments: [
      inputFile('front_template', '--front-template'),
      inputFile('front_render', '--front-render'),
      inputFile('side_template', '--side-template'),
      inputFile('side_render', '--side-render'),
      inputFile('back_template', '--back-template'),
      inputFile('back_render', '--back-render'),
      inputFile('top_template', '--top-template'),
      inputFile('top_render', '--top-render'),
      outputFile('out', '--out', { required: true }),
      outputDir('overlay_dir', '--overlay-dir', { required: true }),
    ],
  },
  {
    name: 'orbit-layout-manifest',
    module: 'orbital-hud-motion',
    description: 'Create a normalized source-independent layout manifest for orbital rings, markers, and arc breaks.',
    runtime: 'python',
    dependencies: [],
    script: 'references/modules/orbital-hud-motion/scripts/orbit_layout_manifest.py',
    arguments: [
      outputFile('out', '--out', { required: true }),
      value('radii', '--radii', 'number-array'),
      value('markers', '--markers', 'number-array'),
      value('arc_break_deg', '--arc-break-deg', 'number'),
    ],
  },
  {
    name: 'register-orthographic-views',
    module: 'orthographic-registration',
    description: 'Measure image extents and emit a shared registration contract for orthographic views.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/orthographic-registration/scripts/register_views.py',
    arguments: [
      { name: 'images', positional: true, type: 'path-array', pathKind: 'input-file', required: true },
      outputFile('out', '--out', { required: true }),
    ],
  },
  {
    name: 'quality-refinement-plan',
    module: 'quality-refinement-autoloop',
    description: 'Classify artifact feedback and propose a measured, fail-gated repair sequence.',
    runtime: 'python',
    dependencies: [],
    script: 'references/modules/quality-refinement-autoloop/scripts/ralph_autoloop_plan.py',
    arguments: [
      value('feedback', '--feedback', 'string', { required: true }),
      value('artifact', '--artifact'),
      outputFile('out', '--out'),
    ],
  },
  {
    name: 'release-readiness-check',
    module: 'quality-refinement-autoloop',
    description: 'Run legacy skill-package release checks. Disabled unless maintenance helpers are explicitly enabled.',
    runtime: 'python',
    dependencies: [],
    maintenance: true,
    script: 'references/modules/quality-refinement-autoloop/scripts/release_readiness_check.py',
    arguments: [
      inputDir('repo_root', '--repo-root', { required: true }),
      value('expected_version', '--expected-version', 'string', { required: true }),
      outputFile('out', '--out'),
    ],
  },
  {
    name: 'sanitize-skill-contributions',
    module: 'quality-refinement-autoloop',
    description: 'Scan skill sources for project-specific terms before reusable publication. Disabled by default.',
    runtime: 'python',
    dependencies: [],
    maintenance: true,
    script: 'references/modules/quality-refinement-autoloop/scripts/sanitize_skill_contributions.py',
    arguments: [
      inputDir('root', '--root', { required: true }),
      value('terms', '--terms', 'string-array'),
      outputFile('out', '--out'),
      value('allow', '--allow', 'string-array'),
    ],
  },
  {
    name: 'reference-manifest-compiler',
    module: 'reference-analysis-validator',
    description: 'Classify reference images and compile dimensions, masks, connected components, bboxes, and centroids.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/reference-analysis-validator/scripts/reference_manifest_compiler.py',
    arguments: [
      { name: 'inputs', positional: true, type: 'path-array', pathKind: 'input-path', required: true },
      outputFile('out', '--out', { required: true }),
      value('mode', '--mode', 'string', { choices: ['auto', 'alpha', 'edges', 'bright_on_dark', 'dark_on_bright'] }),
      value('min_area', '--min-area', 'integer'),
    ],
  },
  {
    name: 'render-overlay-validator',
    module: 'reference-analysis-validator',
    description: 'Measure a reference/render pair and optionally save a blended visual overlay.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/reference-analysis-validator/scripts/render_overlay_validator.py',
    arguments: [
      inputFile('reference', '--reference', { required: true }),
      inputFile('render', '--render', { required: true }),
      outputFile('out', '--out', { required: true }),
      outputFile('overlay', '--overlay'),
      value('mode', '--mode', 'string', { choices: ['auto', 'alpha', 'edges', 'bright_on_dark', 'dark_on_bright'] }),
      value('reference_mode', '--reference-mode', 'string', { choices: ['auto', 'alpha', 'edges', 'bright_on_dark', 'dark_on_bright'] }),
      value('render_mode', '--render-mode', 'string', { choices: ['auto', 'alpha', 'edges', 'bright_on_dark', 'dark_on_bright'] }),
    ],
  },
  {
    name: 'look-fit-report',
    module: 'reference-look-calibration',
    description: 'Compare reference and product crop, brightness, saturation, hue, accent color, and object mask.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/reference-look-calibration/scripts/look_fit_report.py',
    arguments: [
      inputFile('reference', '--reference', { required: true }),
      inputFile('product', '--product', { required: true }),
      outputFile('out', '--out', { required: true }),
      outputFile('overlay', '--overlay'),
      value('accent_hue_min', '--accent-hue-min', 'integer'),
      value('accent_hue_max', '--accent-hue-max', 'integer'),
    ],
  },
  {
    name: 'silhouette-validator',
    module: 'reference-to-3d',
    description: 'Compare reference and render silhouettes with overlap, bbox, and pixel-error metrics.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/reference-to-3d/scripts/silhouette_validator.py',
    arguments: [
      inputFile('reference', '--reference', { required: true }),
      inputFile('render', '--render', { required: true }),
      outputFile('out', '--out', { required: true }),
      value('threshold', '--threshold', 'integer'),
    ],
  },
  {
    name: 'template-analyzer',
    module: 'reference-to-3d',
    description: 'Extract template masks and ranked connected components, preserving long thin line features.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/reference-to-3d/scripts/template_analyzer.py',
    arguments: [
      inputFile('image', '--image', { required: true }),
      outputFile('out', '--out', { required: true }),
      value('mode', '--mode', 'string', { choices: ['auto', 'alpha', 'bright_on_dark', 'dark_on_bright', 'edges'] }),
      value('min_area_frac', '--min-area-frac', 'number'),
      value('min_score_frac', '--min-score-frac', 'number'),
      value('canny1', '--canny1', 'integer'),
      value('canny2', '--canny2', 'integer'),
      value('dilate', '--dilate', 'integer'),
      outputFile('mask_out', '--mask-out'),
    ],
  },
  {
    name: 'seeded-part-masks',
    module: 'source-part-segmentation',
    description: 'Generate deterministic part masks from an explicit seed/part manifest.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/source-part-segmentation/scripts/seeded_part_masks.py',
    arguments: [
      inputFile('manifest', '--manifest', { required: true }),
      outputDir('out_dir', '--out-dir', { required: true }),
    ],
  },
  {
    name: 'segment-source-parts',
    module: 'source-part-segmentation',
    description: 'Segment disconnected or watershed-separated visual components and save masks plus an inventory.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/source-part-segmentation/scripts/segment_source_parts.py',
    arguments: [
      inputFile('image', '--image', { required: true }),
      outputDir('out_dir', '--out-dir', { required: true }),
      value('mode', '--mode', 'string', { choices: ['auto', 'alpha', 'dark_lines', 'bright_on_dark'] }),
      value('min_area', '--min-area', 'integer'),
      value('watershed', '--watershed', 'boolean'),
    ],
  },
  {
    name: 'contour-correspondence-report',
    module: 'texture-driven-mesh-fitting',
    description: 'Measure sampled contour displacement between source and product masks.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy'],
    script: 'references/modules/texture-driven-mesh-fitting/scripts/contour_correspondence_report.py',
    arguments: [
      inputFile('source_mask', '--source-mask', { required: true }),
      inputFile('product_mask', '--product-mask', { required: true }),
      outputFile('out', '--out', { required: true }),
      value('samples', '--samples', 'integer'),
    ],
  },
  {
    name: 'texture-transition-plan',
    module: 'texture-state-animation',
    description: 'Validate ordered texture states and emit an export-aware transition plan.',
    runtime: 'python',
    dependencies: ['Pillow'],
    script: 'references/modules/texture-state-animation/scripts/texture_transition_plan.py',
    arguments: [
      { name: 'images', flag: '--images', type: 'path-array', pathKind: 'input-file', required: true },
      outputFile('out', '--out', { required: true }),
      value('names', '--names', 'string-array'),
    ],
  },
  {
    name: 'wireframe-analyzer',
    module: 'wireframe-to-3d',
    description: 'Extract simplified contours and fitted Bezier segments from a wireframe or technical drawing.',
    runtime: 'python',
    dependencies: ['opencv-python-headless', 'numpy', 'scipy'],
    script: 'references/modules/wireframe-to-3d/scripts/wireframe_analyzer.py',
    arguments: [
      { name: 'image', positional: true, type: 'path', pathKind: 'input-file', required: true },
      { name: 'out', positional: true, type: 'path', pathKind: 'output-file', required: true },
    ],
  },
]

export const HELPER_BY_NAME = new Map(HELPER_CATALOG.map((helper) => [helper.name, helper]))
